## Day 013 作業1：用 Julia 標準函式寫 Sigmoid Function

在 Day 002 時我們曾用 LaTeX 撰寫機器學習常見的激活函式 Sigmoid

$\Large f(x)=\frac{1}{1+e^{-x}}$

作業 1 請使用內建函式 `exp()` 來撰寫 Sigmoid 函式，計算矩陣的 sigmoid 值。

例如：數字 3 的 sigmoid 值。

In [1]:
1 / (1 + exp(-3))

0.9525741268224334

In [15]:
exp(.A)

LoadError: syntax: invalid identifier name "."

宣告及建立矩陣

In [1]:
A = Matrix([1 10 3 4 6; 4 2 4 5 10; 8 5 3 5 9])

3×5 Array{Int64,2}:
 1  10  3  4   6
 4   2  4  5  10
 8   5  3  5   9

In [27]:
function sigmoid(x)
    return 1/1(exp(-x))
end

sigmoid (generic function with 1 method)

In [30]:
#x = zeros(0)
#append!( x, rand(10) )

0-element Array{Float64,1}

In [35]:
a=[]
# 請在此撰寫計算 sigmoid
for i in A
    append!(a,round(sigmoid(i),digits=3))
end

In [40]:
a=reshape(a,3,5)

3×5 Array{Any,2}:
    2.718  22026.5    20.086   54.598    403.429
   54.598      7.389  54.598  148.413  22026.5
 2980.96     148.413  20.086  148.413   8103.08

## 作業2：線性代數基礎運算 Matrix Multiplication 及 Addition

假設 A 是 $n\times m$ 的矩陣，B 是 $m\times p$ 的矩陣，則矩陣乘法的積 AB 是 $\displaystyle n\times p$ 的矩陣。

作業2 請撰寫程式，隨機產生矩陣 $W$ 及 $X$，計算線性方程式 $WX+b$。

【提示】點運算的介紹，可回顧 Day 005 內容及範例。

In [3]:
# 給定 bias 變數值
# 這邊給定的是純量，在矩陣加法中透過 broadcasting 進行加法
b = 1

1

In [ ]:
w = # 請在此撰寫程式

In [ ]:
X = # 請在此撰寫程式

In [ ]:
# 請在此撰寫計算線性方程式


In [22]:
W=Matrix(rand(0:10,5,3))
X=Matrix(rand(0:10,3,2))
b=3

3

In [24]:
W*X

5×2 Array{Int64,2}:
 30  52
  8  54
 34  58
 18  90
  8  30

In [26]:
W*X.+b

5×2 Array{Int64,2}:
 33  55
 11  57
 37  61
 21  93
 11  33